
name: Manual workflow

on: [ push ]
 # workflow_dispatch:

#     inputs:
#       name:
#         description: 'Person to greet'
#         default: 'World'
#         required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: Send tests
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
         # python -m pip install --upgrade pip
          pip install -r requirements.txt
